### PR TITLE
Chore: Update flux to v2.2.0

### PR DESCRIPTION
**Pull request by dzsak**

### CODE REVIEW

**Comment by laszlocph** [comment]
Found one more place, maybe there are more: https://github.com/gimlet-io/gimlet/pull/761/files#diff-ce502593532df90cc3fe7f048aefd750cbdb728bd72aebee620afbc68de2ae76R150

**Comment by dzsak** [comment]
https://github.com/gimlet-io/gimlet-stack-reference/pull/60

**Review by laszlocph — APPROVED** [review]
Thank you.

We need to coordinate the release, so I think I will split this PR and merge it in 2 pieces.

**Comment by laszlocph** [comment]
- Upgrading deps, and bootstrapping the new version: https://github.com/gimlet-io/gimlet/pull/776
- We will start querying the new api versions in the next release of gimlet.

**Pull request closed without merging**
